mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    #管理後台的 URL，將管理後台的網址設定為 /admin/
    url(r'^admin/', include(admin.site.urls)), 
    url(r'^hello/$', 'trips.views.hello_world'),
    url(r'^$', 'trips.views.home'),
    url(r'^post/(?P<id>\d+)/$', 'trips.views.post_detail', name='post_detail'),
	url(r'^message/$','trips.views.message'),

	url(r'^menu/(?P<id>\d+)/$', 'trips.views.menu'),
	#url(r'^menu_detail/(?P<id>\d+)/$', 'trips.views.menu_detail', name='menu_detail'),

    url(r'^welcome/$', 'trips.views.welcome'),
    url(r'^restaurants/$', 'trips.views.restaurants_list'),
    url(r'^comment/(?P<id>\d+)/$', 'trips.views.comment'),

    url(r'^index/$',  'trips.views.index'), 
    url(r'^accounts/login/$',  'trips.views.login'),
    url(r'^accounts/auth/$',  'trips.views.auth_view'),
    url(r'^accounts/loggedin/$', 'trips.views.loggedin'),
    url(r'^accounts/invalid/$', 'trips.views.invalid_login'),
    url(r'^accounts/logout/$', 'trips.views.logout'),
    url(r'^accounts/register/$', 'trips.views.register'),
    url(r'^accounts/register_success/$', 'trips.views.register_success'),
    url(r'^accounts/register_invalid/$', 'trips.views.register_invalid'),

    url(r'^contact/$','trips.views.contact'),

    url(r'^bands/$', 'trips.views.band'),
    url(r'^band_menu/(?P<id>\d+)/$', 'trips.views.band_menu'),
    url(r'^music_comment/(?P<id>\d+)/$', 'trips.views.music_comment'),
    url(r'^random_string/$', 'trips.tests.random_string'),
    url(r'^bitch_face/$', 'trips.views.bitch_face'),
)

mysite/trips/models.py
from django.db import models

#blank = True 欄位檢查允許為空值
#blank = False 欄位檢查不允許為空值
#null = True 寫入資料庫允許為 NULL (Python 為 None)
#null = False 寫入資料庫不允許為 NULL (Python 為 None)

class Post(models.Model): # Django 的 Field 有兩種值可以設定: blank and null
	title 			= models.CharField(max_length=100) 
	content 		= models.TextField(blank=True)
	photo			= models.URLField(blank=True)
	location		= models.CharField(max_length=100) 
	created_at 		= models.DateTimeField(auto_now_add=True) 
	food 			= models.TextField(blank=True)
	habit			= models.TextField(blank=True)
	relationship		= models.CharField(max_length=100)


	def __str__(self):
		return self.title



class Restaurant(models.Model): 
	name			= models.CharField(max_length=100)
	phone_number		= models.CharField(max_length=20)
	address			= models.CharField(max_length=50)

	def __str__(self):
		return self.name

class Food(models.Model):
	name			= models.CharField(max_length=20)
	price			= models.DecimalField(max_digits=3,decimal_places=0)
	comment			= models.CharField(max_length=50, blank=True)
	restaurant 		= models.ForeignKey(Restaurant) #ForeignKey() 繼承方法，繼承餐廳物件		
	def __str__(self):
		return self.name


class Comment(models.Model):
	content			= models.CharField(max_length=200)
	user			= models.CharField(max_length=20)
	email			= models.EmailField(max_length=20)
	created_at 		= models.DateTimeField(auto_now_add=True) 
	restaurant 		= models.ForeignKey(Restaurant) #ForeignKey() 繼承方法，繼承餐廳物件

	def __str__(self):
		return self.user


class Band(models.Model):  #樂團團名
	name   = models.CharField(max_length=50)
	genres = models.CharField(max_length=20)  #風格
	pieces = models.CharField(max_length=50)  #作品
	
	def __str__(self):
		return self.name

class Member(models.Model): #樂團團員
	name 		= models.CharField(max_length=50)
	instrument 	= models.CharField(max_length=20)
	gender		= models.CharField(max_length=5)
	band 		= models.ForeignKey(Band) #ForeignKey() 繼承方法，繼承餐廳物件

	def __str__(self):
		return self.name	
	

class Music_Comment(models.Model):
    content         = models.CharField(max_length=200)
    user            = models.CharField(max_length=20)
    email           = models.EmailField(max_length=20)
    created_at      = models.DateTimeField(auto_now_add=True) 
    band            = models.ForeignKey(Band) #ForeignKey() 繼承方法，繼承餐廳物件

    def __str__(self):
        return self.user

class Thing(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class ImageThing(models.Model):
    name  = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name

class BitchFace(models.Model):
	title = models.CharField(max_length=200)

	def __str__(self):
		return self.title

mysite/templates/band_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>團員</title>
	<link href="//fonts.googleapis.com/css?family=Lemon" rel="stylesheet" type="text/css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="//djangogirlstaipei.github.io/assets/css/style.css" rel="stylesheet" type="text/css">
		<style>
            body {
               background-color: #FFFFFF;
            }
            em {
                color: LightSeaGreen;
            }
            table{
				border: 2px solid ;
				color: #FFD700;
            }
            h2{
				color:#8B4513;
            }

            p{
				color:#008B8B;
            }

            th{
             	border: 1px solid ;
				color:#8B4513;
             }

            td{
             	border: 1px solid ;
             	color: #008B8B;
             }
        </style>
</head>
<body>
	<h2><a href="{% url  'trips.views.band' %}">回前頁</a></h2>

	<h2>{{ b.name }}的團員清單</h2>
	{% if b.member_set.all %}
		<p>共有{{ b.member_set.all|length }}名團員</p>
		<table>

		<tr>
			<th>團員姓名</th>
			<th>樂器</th>
			<th>性別</th>
		</tr>

		{% for member in b.member_set.all %}

		
		<tr>
			<td class="post-content">{{ member.name  }}</td>
			<td class="post-content">{{ member.instrument }}</td>
			<td class="post-content">{{ member.gender }}</td>
		</tr>

		{% endfor %}
		</table>
	
	{% else %}
		<p>Legacy目前無樂團</p>
	{% endif %}

</body>
</html>

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<nav>
	<a href="{% url 'trips.views.home' %}">回首頁</a>

	<!--<h2>歡迎來到餐廳市集</h2>-->
	<a href="/accounts/register/">註冊</a>

	<a href="/accounts/login/">登入</a>

	<em>現在時間: {{current_time}}</em>
	</nav>
	
	<h2>{% block h2 %}{% endblock %}</h2>
	<h2>{% block content %}{% endblock %}</h2>
</body>
</html>

mysite/templates/bitch_face.html
<!DOCTYPE html>
<html lang="en">
<head>
		<meta charset="UTF-8">
	<title>腹黑</title>
	<style>
		body{
			background-image: url(http://ext.pimg.tw/simour/1373950251-394218016.jpg);
			background-repeat:no-repeat;
			background-position: 50% 0%;
		}
	</style>
</head>
<body>
	<h2>{{ full_name }} 測驗結果:</h2>
	<script type="text/javascript">
	var BitchFace = [
		'洗完澡用冷風吹風機吹下體',
		'吃鼻屎',
		'喜愛裸奔',
		'有起床氣',
		'在泳池裡偷尿尿',
	];
	
	var BitchFace2 = [
		'喜愛聞自己的腳臭',
		'吃蚵仔煎不加蚵仔不加蛋',
		'喜愛舔腳趾',
		'睡覺前才洗碗',
		'常常拉屎不自覺墊腳尖',
	];

	var BitchFace3 = [
		'常常拉屎不關門',
		'最愛看忍者哈特利',
		'最愛的AV女優是沖田杏梨',
		'在麥當當吃肯德基套餐',
		'哥哥你不要這樣~',
	];

	var BitchFace5 = [
		'資訊焦慮症',
		'一心三用 (開電腦平板手機)',
		'在捷運上偷放屁',
		'討厭洗澡尤其是冬天',
		'姊姊你不要這樣~',
	];
			

	//var num6 = new Array(3); //3 個結果
		var msg = BitchFace[Math.floor(Math.random() * BitchFace.length)];

		var msg2 = BitchFace2[Math.floor(Math.random() * BitchFace2.length)];

		var msg3 = BitchFace3[Math.floor(Math.random() * BitchFace3.length)];

		var msg5 = BitchFace5[Math.floor(Math.random() * BitchFace5.length)];

		document.write("1. " + msg  + "<br>" + "2. " + msg2 + "<br>" + "3. " + msg3 + "<br>" + "5. " + msg5 );

</script>
	<p>啊嘶，好腹黑哦哦哦</p>
	<br/>
	<h2><a href ="/welcome/">再測一次wwwww</a></h2>
</body>
</html>

mysite/templates/comments.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>美食評價</title>
	<link href="//fonts.googleapis.com/css?family=Lemon" rel="stylesheet" type="text/css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="//djangogirlstaipei.github.io/assets/css/style.css" rel="stylesheet" type="text/css">
	<style>
		body {
               background-color: #FFFFFF;
            }
		table{
				border: 2px solid ;
				color: #FFD700;
            }
            h2{
				color:#8B4513;
            }

            p{
				color:#008B8B;
            }

            th{
             	border: 1px solid ;
				color:#8B4513;
             }

            td{
             	border: 1px solid ;
             	color: #008B8B;
             }
             input[type=submit]{
             	padding:5px 15px;
             	background: #FA8072;
             	border:0 none;
				cursor:pointer;
				-webkit-border-radius: 5px;
				border-radius: 5px;
             }
             

	</style>
</head>
<body>
	<h2><a href="{% url 'trips.views.restaurants_list' %}">回前頁</a>
	</h2>
	<h2>{{r.name}}的評價</h2>
	{% if r.comment_set.all %}
		<p>目前共有{{ r.comment_set.all|length }} 條評價</p>
	<table>
		<tr>
			<th>留言者</th>
			<th>留言時間</th>
			<th>評價</th>
		</tr>
		{% for c in r.comment_set.all %}
		<tr>
			<td class="post-content">{{ c.user }}</td>
			<td class="post-content">{{ c.created_at|date:"Y /m /d" }}</td>
			<td class="post-content">{{ c.content }}</td>
		</tr>

		{% endfor %}
	</table>
	
	{% else %}
	<p>無評價</p>	
	
	{% endif %}

	<br /><br />
	
	<h2>留言吧! 一起加入DjangoBoy：</h2>
		
			<!--<tr>
				<td><label for="user">留言者:</label></td>
				<td><input id="user" type="text" name="user" ></td>
			</tr>
			<tr>
				<td><label for="email">信箱:</label></td>
				<td><input id="email" type="text" name="email" ></td>
			</tr>
			<tr>
				<td><label for="content">留言:</label></td>
				<td>
					<textarea rows="10" cols="48" id="content" name="content" ></textarea>
				</td>
			</tr>-->
			{% if f.errors %}
			<p style="color:red;">
				請確認錯誤{{ f.errors|pluralize}} below.
			</p>
			{% endif %}
		<form action="." method="POST">
			<table>
				
            {% csrf_token %}
            {{ f.as_table }}
            <input type="hidden" name="ok" value="yes">
        	<input type="submit" value="給予評價" >

            </table>
        </form>
        
        <br/><br/>

</body>
</html>

mysite/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Send Email</title>
</head>
<body>
	<h2><a href="{% url 'trips.views.home' %}">回首頁</a></h2>
	<h2><a href="{% url 'trips.views.contact' %}">意見回饋</a></h2>


	{% if success %}
		
		<h2>資料傳輸</h2>

		<p>信箱:{{ email }}</p>
		<p>訊息:{{ message }}</p>
		<p>全名:{{ full_name }}</p>

	
	{% else %}
	<form action="." method="POST">
		{% csrf_token %}
		{{ contact_form.as_p }}
	<input type="submit" value="信件送出">
	<input type="reset" value="Reset">
	</form>

	{% endif %}

</body>
</html>

mysite/templates/hello_fucking_world.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>有時候真想揍你一拳</title>
	<style>
            body {
               background-color: Lightyellow;
            }
            em {
                color: LightSeaGreen;
            }
        </style>
</head>
<body>
	<h1>師大公園地下司令</h1>
    <p>和你約在師大路，一個人坐在路邊等待你的時間</p>
    <p>不知不覺又過了三年，一切都沒改變</p>
    <p>朋友們相聚的夜，抽煙的你和不抽煙的我坐在公園</p>
    <p>除了無止盡的抱怨，一切都沒改變 、一切都已改變</p>
    <p>看著鏡子，裡面的自己，告訴自己還年輕</p>
    <p>戴上耳機，想大聲唱出聲音</p>
    <p>這是我現在的歌</p>
    <p>又  看  到  日  出</p>
    <p>有種豁然開朗的感覺</p>
    <p>--------------------------------------------------</p>
    <p>又  看  到  日  出</p>
    <p>因為冷而縮著身體的我們</p>
    <p>口中呼 出  了 白  煙</p>
    <p>有種豁然開朗的感覺</p>
    <p>有種豁然開朗的感覺</p>
    <p>有種豁然開朗的感覺</p>
    <p>有種豁然開朗的感覺</p>

    <em>{{ current_time }}</em> 
</body>
</html>

mysite/templates/invalid_login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>登入失敗! 逆逆</title>
	<style>
		body{
			background-image: url(http://m-miya.net/blog/wp-content/uploads/2014/10/80-4.jpg);
			background-repeat:no-repeat;
			background-position: center 0%;
		}
	</style>
</head>
<body>
	<h2>{{full_name}} 登入失敗，請重新登入!</h2>
	<br/>
	<p><a href="/accounts/login/">登入</a></p>
	<br/>
	<p><a href="/index/">回登入頁面</a></p>
</body>
</html>

mysite/templates/loggedin.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>登入成功! 逆逆</title>
	<style>
		body{
			background-image: url(http://www.nippon.com/hk/files/b00201_ph02.jpg);
			background-repeat:no-repeat;
			background-position: 50% 10%;
		}
	</style>
</head>
<body>
	<h1>{{full_name}} 登入成功!</h1>
	<br/>
	<h2>歡迎進入</h2>
	<p><a href="/restaurants/">餐廳列表</a></p>
	<p><a href="/bands/">樂團列表</a></p>
	<br/>
	<p><a href="/accounts/logout/">登出</a></p>
	<p>or</p>
	<p><a href="{% url 'trips.views.home' %}">回首頁</a></p>
</body>
</html>

mysite/templates/menu_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>菜單</title>
		<style>
            body {
               background-color: Lightyellow;
            }
            em {
                color: LightSeaGreen;
            }
        </style>
</head>
<body>
	<h1 class="name">
    			<a href="{% url 'menu_detail' id=food.id %}">{{ food.name }}</a>
    </h1>
	<ul>
		<li>菜名: 		{{ food.name  }}</li>
		<li>價錢: 		{{ food.price }}</li>
		<li>評價: 		{{ food.content }}</li>
	</ul>

</body>
</html>

mysite/templates/music_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>樂團評論</title>
	<link href="//fonts.googleapis.com/css?family=Lemon" rel="stylesheet" type="text/css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="//djangogirlstaipei.github.io/assets/css/style.css" rel="stylesheet" type="text/css">
		<style>
            body {
               background-color: #FFFFFF;
            }
            em {
                color: LightSeaGreen;
            }
            table{
				border: 2px solid ;
				color: #FFD700;
            }
            h2{
				color:#8B4513;
            }

            p{
				color:#008B8B;
            }

            th{
             	border: 1px solid ;
				color:#8B4513;
             }

            td{
             	border: 1px solid ;
             	color: #008B8B;
             }
        </style>
</head>
<body>
	<h2><a href="{% url  'trips.views.band' %}">回前頁</a></h2>

	<h2>{{ b.name }}樂評</h2>
	{% if b.music_comment_set.all %}
		<p>共有{{ b.music_comment_set.all|length }}條評論</p>
		<table>

		<tr>
			<th>留言者</th>
			<th>留言時間</th>
			<th>評價</th>
		</tr>

		{% for music_comment in b.music_comment_set.all %}

		
		<tr>
			<td class="post-content">{{ music_comment.user  }}</td>
			<td class="post-content">{{ music_comment.created_at|date:"Y /m /d" }}</td>
			<td class="post-content">{{ music_comment.content }}</td>
		</tr>

		{% endfor %}
		</table>
	
	{% else %}
		<p>Legacy目前無樂團</p>
	{% endif %}

	<br /><br />

	<h2>留言吧! 一起加入樂團人!</h2>
	<form action="." method="POST">
		<table>
				
            {% csrf_token %}
            {{ f.as_table }}
            <input type="hidden" name="ok" value="yes">
        	<input type="submit" value="給予評價" >

        </table>
    </form>

</body>
</html>

mysite/templates/post.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Django Boy's Universe</title>
	<link href="//fonts.googleapis.com/css?family=Lemon" rel="stylesheet" type="text/css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="//djangogirlstaipei.github.io/assets/css/style.css" rel="stylesheet" type="text/css">
</head>
</head>
<body>
	<div class="header">
        <h1 class="site-title text-center">
            <a href="/">Django Boy's Universe</a>
        </h1>
    </div>
    <div class="container post post-detail">
    	<div class="post-heading">
    		<h1 class="title">
    			<a href="{% url 'post_detail' id=post.id %}">{{ post.title }}</a>
    		</h1>
    		<div class="date">{{ post.created_at|date:"Y /m /d" }}</div>
    	</div>
    	<div class="location">
    		<i class="fa fa-map-maker"></i>
    		<span id="location-content">出沒地點：{{ post.location }}</span>
    	</div>
    	<div id="map-canvas" class="map"></div>
    	<div class="post-content">
    		自我介紹：{{ post.content }}
    	</div>
        <p></p>
        <div class="food">
            喜歡的食物：{{ post.food }}
        </div>
        <p></p>
        <div class="price">
            好習慣：{{ post.habit }}
        </div>
        <p></p>
        <div class="is_spicy">
            感情狀況：{{ post.relationship }}
        </div>
        <p></p>

    	<hr class="fancy-line">
    	<img class="photo" src="{{ post.photo }}" alt="">
    </div>
    <em>{{ current_time }}</em>
</body>
</html> 

mysite/templates/register_invalid.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>註冊失敗</title>
</head>
<body>

	<h2><a href="{% url 'trips.views.register' %}">註冊失敗，請重新註冊</a></h2>
</body>
</html>

mysite/templates/register_success.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>註冊成功!</title>
</head>
<body>
	<h2>註冊成功!</h2>
	<p><a href="/accounts/login/">歡迎你! 請登入!</a></p>
	<p>登入時間:{{datetime}}</p>
</body>
</html>

mysite/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>張開你的腿</title>
	<style>
		body{
			background-image: url(http://pic.pimg.tw/lovetabris/1383764945-2767260218.jpg);
			background-repeat:no-repeat;
			background-position: 60% 0%;
		}
	</style>
</head>
<body>
	<h2><a href="{% url 'trips.views.home' %}">回首頁</a></h2>
	<form action="/bitch_face/"  method="get">
		<h2>長大實在是很麻煩的一件事啊</h2>
		<br/>
		<h2>上學上班實在無聊惹</h2>
		<br/>
		<h2>不如來測看看你腹黑的一面吧!</h2>
		<br/>
		<label for="user_name">請輸入姓名:</label>
		<input id="user_name" type="text" name="user_name">
		<input type="submit" value="檢視結果">
	</form>

	<em>{{ current_time }}</em>
</body>
</html>